# Generated by Django 2.2.5 on 2019-09-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20190913_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(blank=True, default=True, verbose_name='É da equipe?'),
        ),
    ]
