# Generated by Django 2.2.5 on 2019-09-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gmud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('cliente', models.CharField(max_length=30, verbose_name='Cliente')),
                ('criticidade', models.CharField(max_length=30, verbose_name='Criticidade')),
                ('resumo', models.CharField(blank=True, max_length=400, verbose_name='Resumo')),
                ('data', models.DateTimeField(verbose_name='Data e Hora de Realização')),
                ('datacriacao', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('procedimento', models.FileField(upload_to='procedimentos/', verbose_name='Procedimentos')),
                ('servidores', models.CharField(max_length=100, verbose_name='Servidores')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'GMUD',
                'verbose_name_plural': 'GMUDs',
            },
        ),
    ]
